<?php

namespace DoraBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{

    public function getratings()
    {
        $q=$this->getEntityManager()->createQuery("SELECT AVG(m.rating) as average from DoraBundle:Rating m ");

        return $query=$q->getSingleScalarResult();


    }
}
